apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  values:
    authentik:
      secret_key:
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: authentik_secret_key
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
      error_reporting:
        enabled: false
      postgresql:
        password:
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: authentik_postgresql_password

    server:
      ingress:
        ingressClassName: external
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - &host auth.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *host
            secretName: authentik-tls

    postgresql:
      enabled: true
      auth:
        password:
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: authentik_postgresql_password
    redis:
      enabled: true
