---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretKeyRef:
            name: authentik-secrets
            key: authentik_postgresql_password
        - secretKeyRef:
            name: authentik-secrets
            key: authentik_secret_key
    authentik:
      secret_key: ${AUTHENTIK_SECRET_KEY}
      postgresql:
        password: ${AUTHENTIK_POSTGRESQL_PASSWORD}
    redis:
      enabled: true
    postgresql:
      enabled: true
      auth:
        password: ${AUTHENTIK_POSTGRESQL_PASSWORD}
    server:
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.8@sha256:217c47c886965474f5c234b5a35ed008f53b39ea90a3088b31c0da98e1f9284d
          envFrom:
            - secretKeyRef:
                name: authentik-secrets
                key: authentik_postgresql_password
            - secretKeyRef:
                name: authentik-secrets
                key: authentik_secret_key
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: auth.${SECRET_DOMAIN}
            paths:
              - /
        https: false
    prometheus:
      rules:
        enabled: true
# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: authentik
# spec:
#   chart:
#     spec:
#       chart: authentik
#       version: 2025.2.1
#       sourceRef:
#         kind: HelmRepository
#         name: authentik
#         namespace: flux-system
#   interval: 15m
#   timeout: 5m
#   releaseName: authentik
#   values:
#     authentik:
#       secret_key:
#         valueFrom:
#           secretKeyRef:
#             name: authentik-secrets
#             key: authentik_secret_key
#       # This sends anonymous usage-data, stack traces on errors and
#       # performance data to sentry.io, and is fully opt-in
#       error_reporting:
#         enabled: false
#       postgresql:
#         password:
#           valueFrom:
#             secretKeyRef:
#               name: authentik-secrets
#               key: authentik_postgresql_password

#     server:
#       ingress:
#         ingressClassName: external
#         enabled: true
#         annotations:
#           external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
#           cert-manager.io/cluster-issuer: "letsencrypt-production"
#           nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#         hosts:
#           - &host auth.${SECRET_DOMAIN}
#         tls:
#           - hosts:
#               - *host
#             secretName: authentik-tls

#     postgresql:
#       enabled: true
#       auth:
#         password:
#           valueFrom:
#             secretKeyRef:
#               name: authentik-secrets
#               key: authentik_postgresql_password
#     redis:
#       enabled: true
