---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 15m
  url: https://charts.goauthentik.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: networking
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  values:
    authentik:
      secret_key: "PleaseGenerateASecureKey"
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
      error_reporting:
        enabled: false
      postgresql:
        password: "ThisIsNotASecurePassword"

    server:
      ingress:
        ingressClassName: external
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - &host auth.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *host
            secretName: authentik-tls

    postgresql:
      enabled: true
      auth:
        password: "ThisIsNotASecurePassword"
    redis:
      enabled: true
