apiVersion: v1
kind: Service
metadata:
  name: qbittorrent

spec:
  selector:
    app: qbittorrent
    part-of: qbittorrent
  type: LoadBalancer

  ports:
    - name: webui
      port: 8080
      targetPort: webui
    - name: bittorrent
      port: 6881
      targetPort: bittorrent
      protocol: TCP
    - name: bittorrent-udp
      port: 6881
      targetPort: bittorrent-udp
      protocol: UDP
