apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
