---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent
  annotations:
    nfs.io/storage-path: "data01/qbittorrent"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-series
  annotations:
    nfs.io/storage-path: "data02/downloads/series"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-movies
  annotations:
    nfs.io/storage-path: "data02/downloads/movies"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: downloads-movies4k
#  annotations:
#    nfs.io/storage-path: "data02/downloads/movies4k"
#spec:
#  storageClassName: managed-nfs-storage
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi
