apiVersion: v1
kind: Service
metadata:
  name: notes-app
  namespace: utilities
  labels:
    app: notes-app
spec:
  selector:
    app: notes-app
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 10000
      targetPort: 10000
