apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rutbergphilip
  services.yaml: |
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        cpu: true
        memory: true
        network: default
    - grafana:
        url: https://grafana.rutberg.dev/?orgId=1
        username: ${GRAFANA_USERNAME}
        password: ${GRAFANA_PASSWORD}
    - authentik:
        url: https://auth.rutberg.dev
        key: ${AUTHENTIK_KEY}
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: xl
        locale: se
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h24
  docker.yaml: ""
