apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rutbergphilip
  services.yaml: |
    - Cluster Management:
        - Authentik:
            href: https://auth.rutberg.dev/
            description: Authentication service
            icon: authentik.png
            widget:
              type: authentik
              url: https://auth.rutberg.dev/
              key: JEK0WeLw5Pv5CCfIZRSDH3lXwitkVt9DCXK2ubifnEbSTD9BEHIGBvtiML9V
              users: true
              loginsLast24H: true
              failedLoginsLast24H: true
    - Observability:
        - Grafana:
            href: https://grafana.rutberg.dev
            description: Grafana dashboard
            icon: grafana.png
            widget:
              type: grafana
              url: https://grafana.rutberg.dev
              username: ${GRAFANA_USERNAME}
              password: ${GRAFANA_PASSWORD}

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: m
        locale: se
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h24
  docker.yaml: ""
