apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rutbergphilip
  services.yaml: |
    - Observability:
        - Grafana:
            href: http://grafana.rutberg.dev/
            description: Homepage is awesome
            password: ${GRAFANA_PASSWORD}
            username: ${GRAFANA_USERNAME}
        - Authentik:
                  href: http://auth.rutberg.dev/
                  description: Authentication service
                  key: test-token
                  widget:
                    type: authentik
                    url: http://auth.rutberg.dev/
                    users: true
                    loginsLast24H: true
                    failedLoginsLast24H: true

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: xl
        locale: se
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h24
  docker.yaml: ""
