apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: homepage
  labels:
    app: homepage

spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 250m
          volumeMounts:
            - name: homepage-data
              mountPath: /app/config
            - mountPath: /app/config/custom.js
              name: homepage-data
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-data
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-data
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-data
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-data
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-data
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-data
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-data
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-data
          persistentVolumeClaim:
            claimName: homepage-data-pvc
