---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - ./secrets
  - config.enc.yaml
  - deployment.yaml
  - storage.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml
  - rbac.yaml
