apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-data-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
