---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage

spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: latest
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/rutbergphilip
      services:
        - My First Group:
            - My First Service:
                href: http://localhost/
                description: Homepage is awesome

        - My Second Group:
            - My Second Service:
                href: http://localhost/
                description: Homepage is the best

        - My Third Group:
            - My Third Service:
                href: http://localhost/
                description: Homepage is 😎
      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
        - grafana:
            url: https://grafana.rutberg.dev/
      kubernetes:
        mode: cluster
      settings:

    serviceAccount:
      create: true
      name: homepage

    enableRbac: true

  ingress:
    enabled: true
    ingressClassName: external
    annotations:
      external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      nginx.ingress.kubernetes.io/auth-url: "http://ak-outpost-authentik-embedded-outpost.home-automation.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.rutberg.dev/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid"
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    rules:
      - host: home.rutberg.dev
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: homepage
                  port:
                    number: 10010
