apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utilities
  name: trilium
  labels:
    app: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: zadam/trilium:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          env:
            - name: TRILIUM_DATA_DIR
              value: "/data/trilium"
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: TRILIUM_PORT
              value: "10020"
          resources:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 250m
          volumeMounts:
            - name: trilium-data
              mountPath: /data
      volumes:
        - name: trilium-data
          emptyDir: {}
