apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utilities
  name: trilium
  labels:
    app: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: zadam/trilium:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10020
          readinessProbe:
            httpGet:
              path: /
              port: 10020
          env:
            - name: TRILIUM_DATA_DIR
              value: "/data/trilium"
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: TRILIUM_PORT
              value: "10020"
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 250m
          volumeMounts:
            - name: trilium-storage
              mountPath: /data
      volumes:
        - name: trilium-storage
          emptyDir: {}
