apiVersion: v1
kind: Secret
metadata:
    name: authentik-key
stringData:
    api_key: ENC[AES256_GCM,data:Hwnnw2Y54yYauoY+EAptzNt82hWPWg==,iv:1SlkofTKj91Vj825zNhRohqN+DpRZKBFA8fy7cRMm5I=,tag:3tgrqCSiNJBi0rQ/ZZ/uJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM0VrelVwUlBVTjQwa3NS
            ckNuQWs3QlNYRWp3MGFNYUtvSTJvTUYzTVJnClN6M3cwQmRSRHd3YUVhU2NPWnRJ
            RVJBR0NLWWpJa2lVSVBKY3pSY2lQQlUKLS0tIGU1bjQ1SzFwYWc1bVRoeW1TSWJT
            aGg3RktXeFVudW5aWkRVN2J1UEtnSWsKHUibysYgc+XpdnjOaYKKTewRCnRnsZN1
            SirwX2KkmXBDT5GPwxj+3RtPO9epEUcLBRY+kLAcXDqrfDlr+q1teg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-04T11:08:52Z"
    mac: ENC[AES256_GCM,data:qYNFnSzqf6cibFX/O6KsbjIdzS+VgGibQjtXXzDJ/9NsyXJXculMUF7GheK2HPIBVioSuH+vMLfSAmR+cgYCCeoCOEtWHk6EQg0gohFlD8zyDlTJcj5TvitVMaNFJdP+BQzJ3qhMyuudeBzpx5sGEpHJjf8918a6qW2h2pPrSJE=,iv:cJPp0njINdx0JRym+Yuc1l37k432j3bWZ3K0Ujoswaw=,tag:TNXyiJRYA1KoWNE3LuexXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
