apiVersion: v1
kind: Secret
metadata:
    name: homepage-config
stringData:
    kubernetes.yaml: ENC[AES256_GCM,data:FUVY2+Sg53cJl7Md0CQ=,iv:9l2GToyzG47TlkAFAulXQYO7NOA7UVJFzBsWFYOBnCE=,tag:VT/L6UgE5S3a4+TiX2NWig==,type:str]
    settings.yaml: ""
    #ENC[AES256_GCM,data:Nz3duqSfqBppyENsofO/Gg==,iv:SMBScr3JwaSy9s3kQIvwpOcalblZLLkpGy4+DK1MJN4=,tag:BMVtrNVGNlQbu/OoU2pYrg==,type:comment]
    #ENC[AES256_GCM,data:W3FyTBpkQrFh4bRZ,iv:Z6JYwFyX8tBWkB+NoMQvw7fyhsmKBwuQc/F4yZxGKY0=,tag:GECMylYcHnHzspKSZaldDg==,type:comment]
    #ENC[AES256_GCM,data:2Tg7MUxzdWTK7hcjog==,iv:5ecGFL/4xloPrJTXvlTzV/y+4WaDCkEXwuzVOlsiMrw=,tag:UaEypDYfQsK23e5pcx0UBA==,type:comment]
    #ENC[AES256_GCM,data:tkaG5aeko9hhvNtei9+VWXlcwFNMnx3h9cKxtJ1rtaAhSWkNGRA=,iv:6GzinJ+c1jRSxeNQReQ0ugD8ovKUDgmTg/jvmzICBzk=,tag:2pSXHv3BM3YEXnVto/ThDw==,type:comment]
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: ENC[AES256_GCM,data:8QO/PFePfct+tFxJgmGabA/yzMpwFGllVduik0yI/kJbt9ndsD3pQuVvT0s11H+Ig0bYmRy+1esbcD+Wh6iqpt+BfVVk326H978NypvwZsRoud/5vwnN3/wh8sMYU08=,iv:j+6LoBK6fdxus8ylduG+DUKbXXXKwOfp+JRbaQxRS/8=,tag:f/6T/S3bCJB63JmpFy8ppQ==,type:str]
    services.yaml: ENC[AES256_GCM,data:wKzyNC/NbtjxuKKwdVm0OS/N3MiGYUCOc2ZH0QVdnpS7ttSgtJ7x/ZUO4CdnBVfRm78u08QVeT88ZHBdYvRsO6M66FrzN+7eRldvznF0mXbej25vjITPDX9/Uq9RnF3pY7iG8bFHj0EPUWglhxLYSNUSoD8OW3DqumRtViH45AO8vfQd7reG1xuGy+ZR7N9gMbeJO/HGM6OqH9AF7W2Oco8GtkGdVLKMKhsGi+ru6iTPPR//fPHwxjvsvIoYCW18SShYC5a0N6WmD8chcjjEd434fV6/iR8g2vNPQK6NOnVahhPzvS5arF+nMwz2TzPwNNurzeYignea1EOCJ382UKpm5VjNuLh0ijRNsLgXqjG9Qe+c7ztbmniWQMXqD+FRxYHeJ2UZQt9FRJbMAamn1vkzQ6z7G+TolIGsdmKs5bh2FrSjpJ0xmHSg+E4hPuhYSf5M95ySLJ2Msn3+/tWdzGLEh3dtzpHrZflIwiRc2G7CQraRz9ZzTyjDiqm8rTt9ZwrT3DDVR+oV9TFo/2afN3C6+JOt4WzwZPf9bthOxLaVML5niOfCDF1fxTXu+VJqQVY0Wd9QGWKs9ZsC+wtbhXoDgndNcqxLaq84pcEA098DMcG/vrn+tI+LoheG51Qe3FKjOqcwMhtnGLnHt+14UFKRG+KRdiUxfzCMgccBYBQkgct3j9w6FklCdnQwzLLO7utTIwfdBffHZKjtoiqCLyQwz3lgGBPlUKx5Fpz8KdJypeYDXKMR4lsXVjbPBx8+frXJZA3oiIUUV/b7cC2c5ktIlteSWr8D1fZQHdacd5V7JPcAG605cbvfb26ld046U3B1o/2vJ0cgJ3Le4nUWAbyR8loRX6jpF382X71ZmylLa9u2xPWaFfh2gELvCkSr1LsQfvrLgUbD2cWIxRkmV8vp6YlnkWWUI8nES8zkQJxZX/TsIL54igu8B1dK3wxIH1Br0rEDI51gjOCmFSf5E1LyjseUg2RF8P1mMfl0kA86eUq0JJGJL3OxF9GEZX9c4I8En81xHaMWpSJTPKFT8BMuWwsXZB2NKfIohV8J4wiYERUOTx6X+JbZ4bu6Li3uUny3Zi7JqSdFhp+vlWit7AJGD5z7eEzD0lgTEzHu+vO8oPli8CaBzbqlcQNS62ObiCGEgnvNB4VA4JT19kGAgaq56RqON117bVkKs8HTZngXmtI4XwyZgROb04MTNOy66cBkRLJTFn8P64cNA5BR1N0fzDvtJFJG3APd8hDZRQy6VrgZs8gYeOtuH8vy4eByT6U1pb6MCSO0HLqcEBwPKK439iR9cPLAwNcTyni6fbratRbW7FjXuHB8XNI=,iv:3V1tOtB+0XEHZi1ZNQY5UL5Vsc8KcIb6e6Y9vD3tSFk=,tag:jys6UnIEnDu3tPv647l8dQ==,type:str]
    widgets.yaml: ENC[AES256_GCM,data:BazM4XrWhSBT84G9r9YcTiV7h6m23901yxNQjGukDtsjaZGqh5f5JhE2HmHHmbGR1sVKbWs8HT7zFe5E9c5TobZrs3mdOSrE0SM8Ww5Xkpd9OlzthBtLJFW51WAWuJg1pHWGNop/tsYTQP6JMlw8JKh6jj5gyyJNXBR0anTHS4NPFx0qIKYLpTCojWnlVetjcuNUZRslT1FIjO41JBTqTc5RsfXhYS5tLsFCndWCKofBZK8Ysg/KVSau2atkn0YjzbtAGdHBFb4gy8zuooMSCU3di4HWCRuCZ8QGvCdShDOzQwHK9I8YQuuDaH9iusdBs0Si5AppSW4KCYMtCYKu6gWbYONC5ynshH16nytyUC8KTtebPZsWtcxiKflExQhr6VrDZiYZrCHHbvgg3lG5Og5PgVDyYj5jbwzjENJsNZXUApsNS3mtUdBOdWFYDEL5ngnwHtj08lJHQGFRAEfqf4Ua1fEh/vuvKm/o5yg8QAPhOPQO3ZK2aqgM13+9Sl/02eAJDrPNAfiOLcB9XzS2+PmAX1+qEXUhnQksXz/nHBcbZ1rtXrBsUSKqR7oEM8M8Qgr0NALZjeUDhCcNQQ+JSqEgUDPqjSNj+4HlVnqeioLunwMjgZFWx5ds,iv:lQJxImBtmyZ/cTiJCvtbTvZPpe//AUChsURRJYEHU38=,tag:KVD9+TybCK3u5Kpays9Ciw==,type:str]
    docker.yaml: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZEg5QllpL3pqYU8yTFNC
            YWlUQUZNSGE0VlkzbDBrdUNoYkJTbGdDL1NZCmNuK0RSN0ZMUEJjVGxOUm9ySXRl
            Q05OQ2lFcXFOZ21uUU90WHlyRGRXUk0KLS0tIHdxMEp6alZGWFBpZzdhRm41NXQx
            Ly8zZjNpc3RudEJWWHVjRERBS3k1SXcKimpt7oB98ErUwGNU0t9+qKndWPLQ7UBo
            xcGL6SZXvCKpnA96X4i229lH2MlDCEclcKBHqfuIxy6BYab7oPTUFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T10:50:20Z"
    mac: ENC[AES256_GCM,data:e4HEY3uHYbpxCOv09jZJhvQpFZypGpYmEHkEbBQxO1sYeeVK/B26SModWMzu0Iz9JaG70Sn7nL35XzvSOKzJn6ICM0nH8M4a+U69VVvmPeWfVwvdo0ojjVb3X9GgH4MK9h7FLMmTWQ+p0xggtrPC55NDsxi8sFfB6IRc3xKmMVM=,iv:QO+ZbdUlBGVciPDPK1rYng2WWQ4CLm80aDH1f0seOAQ=,tag:XYyECDxZhoiq/GmyGSENQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
