apiVersion: v1
kind: Secret
metadata:
    name: homepage-config
stringData:
    kubernetes.yaml: ENC[AES256_GCM,data:yNKUsdQnn+et6X3PnxA=,iv:ju3mE7IVes8G/cnIZygA0RKvPOJfXin7ssBig827RLg=,tag:YUu1XBdNypLgxBSlCr0S0g==,type:str]
    settings.yaml: ""
    #ENC[AES256_GCM,data:NFr7lDQnHG8OZXOa7AJoGA==,iv:m3/ww2LkwRh4ztwRWs8o+XqWqo+Mx5z9VTi7dSMjgpw=,tag:lTxiFDE1uHay/XXreT1fOA==,type:comment]
    #ENC[AES256_GCM,data:ciTHYmeL8Zg0BoJP,iv:MIABRYZ5mTf9knJpGGNZa+/+29mVgp0iurgCtudjEhE=,tag:hhU0LOwiykk56M4D04vB/A==,type:comment]
    #ENC[AES256_GCM,data:EKOEB8M/0ncebnt0YA==,iv:+OxHHHn2+Yu+iwzBakAfCV9vbt97ZP5DKiZ4p+2v2Yo=,tag:/rcbDKa3MsrHSttmtrbFDA==,type:comment]
    #ENC[AES256_GCM,data:jXgtjXiuESvH/mTiGE6rRw/1qQMbSiMVnPfPtOipnsLgyHgcdJs=,iv:VcuRl9uLBXpZMdUUuOADSHdu1oVc7rtY1FZsMr7jDog=,tag:KmdgD0HRVE89VEGtsmfpTA==,type:comment]
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: ENC[AES256_GCM,data:wZ7LFU+WIRc2toJ0vZcVtOVTDZ5QLqp3DMlnlPeYQC2zPPOD7IKGJ7x6sqv+ooUcCfwYiIyx+F2+EnsL9JuRcGRNSes7eUTJVC3EQN1kTvH09GQAAmELeysXur85Tmo=,iv:eubDqG8bKYUHSpI4erKeTn5g6bLxTrXL0ln/he+QHvE=,tag:MRXn0GiaSCxSAT62ValdTA==,type:str]
    services.yaml: ENC[AES256_GCM,data:IzHi7DPYZRJFhmuLMYFZVt4qEiBnmjtg8jGnsLBSaLTz9MwjpTEc1h5t63ryDyEsMhDZkO61H+sH7tW4jpbWA0wv2BxFkreHavYk4NhloPRuDSVdQJBb65a052Ph2mxHIgOEgUx5bnyP1t8g9v8oBQOF2mWWoFSZj953jPldL59td+W8tNdpZ6ogE9aTgROJlNNTIu5qv+QkU1WncQBdB1cctZ+KIXfEaI0Mfx3KmweXyagsmg0mMOhZw8N15PiCakMgA8FuZgZpER+KF+cSpXkwGmWrSXBBrHIDLNuRxCEF8sCbq7ydxjA29p8STLaKGdznH6L6y5uyQ7CJlLkKnLT4YWawfrytbyrG4R9BLfDVmIjPvt/dEb86iPoffOuSD8mchlHztZBjt4MXlNk/7TFgOtOFNAXtkABlBiRNPKCy5hWyEeb42u5RnpjPAS7eo1YXoiIaci7XynU8E0V0ylGnzih+3cIsxCODFkgUGNPNd27AqT1hFz5Dm1WLrF2tt4kA0J7v6tq0wgKkixYVzKed2PPPwBi6lGsgEmS4X+J6+PMYT9BLajBokv4rdX/E8DzRxyQ0AkQ0F+JLsnbpeK5rAySfOCakkl+lxZfBX1AO7/Z1qOItIdu6v6iHa42h8iFdEOlew9L0q30dWYNFKkCwpSMnGw/X9mgioHssYakOoMS9rhY5vw1Qgh/IN2XXrKkCpt0ooMbB+TVO9JcFOC8Ew7j6sh8KWczLOq68iLU7Kvw/5li1jlBK1b8gcpi1YEAjffvLyjdOUBqGX6xUZsBOMTEoZQfuK2bwBKc4bNA1XFvw+ynVD8WeBLVMEU5HdDOPv2p4ybtaC89BKNQLIyUMX4o79Ep+KS5dPcE8Fv3Vio4oObAi0YGayypVtFdQq1JhLjabKyZozXQPEb8UoU8vmMO7WIGpZTI=,iv:8mgMlWEEzi89piCPDKr770NFLfvmTL/X+iPQbHuMTmg=,tag:SmeQkXuA/kJvGA1Fhs3Y9g==,type:str]
    widgets.yaml: ENC[AES256_GCM,data:eVpBs5sHjvn4Y2VWs/i4LCvlXgghLZ9ukFRltXhJr9bjaM5InTdhYhfHS4oU5Pdx989Ytep0aQ3B9v5oDFIGPJySraXTDnDRE+E3bB1vfKC1hEFYwXcHHZ05wewtlPbc/TxCovfuvX9j8ZU+q1zKY/O2yw7WmwYp9eXCQHsH/hzVKDc3Q6QXwmECjybBUUwpKz2ByDACFP2/7edatuXDEQdyWY5g7Nkd+znbQRxdcP15KGuAyZjx51tY5VvY9xxHQTQeAoDtnu3lw8/T3tR5mDnQLt4hTOvc6qdt+ss1Sp7ptuT9pVbcTBppkDdpmYNQkNhmfAH07Psti3cFc8GMQlGSEzDttJpGCz1TuuHPcop+GXPMPItOhh1niOhgFFxciZsPVfTdC6GEGLn7qI742OJ2lDjTPSU+/gGUG29GE+42n6EG7j3m/ZV5V9s5tS3O8bf70i8aHEhrIkQq+vc0aS9HI9pGIEPKURU3FG2Sn8lWqNshgvWwNUccw8IuiAXEa9P4pusLeuEzMgyfoKUZj9VbGwbSwPS/aae3mMJ0Dm3w+e5pC+3UIoMn2MNQhNIqz6u02YJ5UqaweXGtDFrqRj+VwPhMr91e9+D4q6nL8UAF6R7XMIR7x2Uw,iv:pOoqZqsQI2Ykbqpbv9dJBfVBVoFgB+3B6WtobhCw50c=,tag:tif2gvArd39GY/xHVsKVrQ==,type:str]
    docker.yaml: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMlhrT2NLaUpVYWgxOXZy
            RnY0eDlyRnZidkhRdTg2UXZRaXd2Nm5qV3hvCmxqMEpLWmxVd1BDbjg0eWZMbWtU
            TER6eUZVQW4yYlZhdnlxVVJZTy80dTgKLS0tIFQzOFRoT05Ca2dTcjBhSXIxYkMx
            Ulp0NlFocm9xeFI1dUFkSSt0MGVTRWMKKV5KrM1HcaXfQ3WvaWu1RrYon6a4hPXH
            rvLhFBOICrkFS/eI1dpJvaqlKT73mJxSNWREf8ScHW2aVH0LKOwc3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T20:48:30Z"
    mac: ENC[AES256_GCM,data:pF1VH5DL7tcPRfvONi8ImST32KJqdv90+gucJR9P9QeNxjquOa8KASbcez/hWDXkpG+HavlpKqALabtz0Al83ydXewBrv0OoPTymptyHDgSkKfoOfptL1y6TBCTs4X3uzbJl/ra3IP76/yW8U1LYOZeaTjvW8xY1FEsWsg0Zztg=,iv:rP280BWCv8n4QK7n9ehpNOkgLlb1toOxOnGnJ0ZYbr0=,tag:jOf7V+IHuQ7OkRfM7mYfnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
