apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
stringData:
    username: ENC[AES256_GCM,data:l433NaUdpUVhORrylD6nVgVpt+VAEIL7gQ==,iv:8PDI5872AgsbU0WAfRMcN42EsLrE7t9RlSIbr08vSzY=,tag:q5aN8DlSAByQWQCLegu6CQ==,type:str]
    password: ENC[AES256_GCM,data:jIFfjfCPhIbGZJQ=,iv:vPmoWye6PtAocrYwptAcA/lbyg+OpSNPpeJ3WZrbJMM=,tag:DTO1zIq0o8Ln/Y8FS0BptQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUlFLWHNNOFVzWU9ZbkNB
            alBLclBsQ3VNMG1ZRm1XV280bDVWMjhRdGc4CmE0aDFJY3g5b1Uva3R0b0JiM1RE
            ZnV3NEtEc21UVnZHU2N6OGlPN1FGVE0KLS0tIHRkMlVpN1RMNXl0N2tYVjMveEt6
            ZkhxdDVwSkhZN0RHUkR1eTByRjV5dEkKOI8QGzrSVhtJXN4LpSCt9ygI+mGwTO9Z
            Vmu9Xyo4DDy1M7VycyhSCQcePRBZs5jADzKU7S1MYUKJak3tkxKLmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-04T09:17:05Z"
    mac: ENC[AES256_GCM,data:tI47a9OM3CIjcPBGUx/4XJL6xUwWbRuxorZQMck0WVPcYhpTuOft8dySDREHtwLmtSne9Bo0TIEKjvgLEdUuIIR87VD+Af3irlannJpZAkpjKkv9nGXaMsVctuvcUvxdXr/YAci/XgwwwmKXfFSPWIgYEJI+uLr3nsIzBClJ3jE=,iv:1TgUL8eP/JXnsZBxJwxtYZh1ItNaZTNmxTNnzjs75yk=,tag:8tEvNVFq9jYm1o5JJl6+dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
