apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: home-automation

spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser

    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        allowPrivilegeEscalation: true
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:s6
          ports:
            - containerPort: 80

          resources:
            limits:
              memory: 800Mi
              cpu: 400m

          volumeMounts:
            - name: extracted-movies
              mountPath: /srv/movies
            - name: extracted-series
              mountPath: /srv/series
            # - name: filebrowser-db
            #   mountPath: /database/filebrowser.db
            #   subPath: filebrowser.db
            # - name: filebrowser-config
            #   mountPath: /config/settings.json
            #   subPath: settings.json

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

      volumes:
        - name: extracted-movies
          persistentVolumeClaim:
            claimName: extracted-movies
        - name: extracted-series
          persistentVolumeClaim:
            claimName: extracted-series
        # - name: filebrowser-db
        #   persistentVolumeClaim:
        #     claimName: filebrowser-db
        # - name: filebrowser-config
        #   persistentVolumeClaim:
        #     claimName: filebrowser-config
