apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: home-automation

spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser

    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:s6
          ports:
            - containerPort: 80
          args:
            - "--auth.method=noauth"

          resources:
            limits:
              memory: 512Mi
              cpu: 500m

          volumeMounts:
            - name: filebrowser-data
              mountPath: /srv

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

      volumes:
        - name: filebrowser-data
          persistentVolumeClaim:
            claimName: filebrowser-pvc
