apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utilities
  name: notes-app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: zadam/trilium:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
          livenessProbe:
            httpGet:
              path: /
              port: 10000
          readinessProbe:
            httpGet:
              path: /
              port: 10000
          env:
            - name: TRILIUM_DATA_DIR
              value: "/data/trilium"
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: TRILIUM_PORT
              value: "10000"
          resources:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 250m
          volumeMounts:
            - name: trilium-data
              mountPath: /data
      volumes:
        - name: trilium-data
          emptyDir: {}
