apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utilities
  name: notes-app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: ghcr.io/enchant97/note-mark-aio:latest # {"$imagepolicy": "utilities:notes-app"}
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
          readinessProbe:
            httpGet:
              path: /
              port: 10000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: notes-app-secret
            - name: BIND__HOST
              value: "0.0.0.0"
            - name: BIND__PORT
              value: "8000"
            - name: DB__TYPE
              value: "sqlite"
            - name: DB__URI
              value: "/data/db.sqlite"
            - name: TOKEN_EXPIRY
              value: "259200"
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 250m
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          emptyDir: {}
