apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: notes-app
  namespace: utilities
spec:
  image: ghcr.io/enchant97/note-mark-aio
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: notes-app
  namespace: utilities
spec:
  imageRepositoryRef:
    name: notes-app
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: notes-app
  namespace: utilities
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "Automated image update by Flux"
    push:
      branch: master
  update:
    path: ./kubernetes/apps
    strategy: Setters
