---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  targetNamespace: security
  interval: 1h
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    authentik:
      error_reporting:
        enabled: false
    server:
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "auth.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    postgresql:
      enabled: true
    redis:
      enabled: true
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_SECRET_KEY
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_BOOTSTRAP_TOKEN
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: POSTGRESQL_PASSWORD
      volumeMounts:
        - mountPath: /data
          name: authentik-data
      volumes:
        - name: authentik-data
          persistentVolumeClaim:
            claimName: authentik-data-pvc
