---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  targetNamespace: security
  interval: 5m
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: 2025.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    authentik:
      secret_key: ${AUTHENTIK_SECRET_KEY}
      error_reporting:
        enabled: false
      postgresql:
        password: ${POSTGRESQL_PASSWORD}
    server:
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "auth.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    postgresql:
      enabled: true
      auth:
        password: ${POSTGRESQL_PASSWORD}
    redis:
      enabled: true
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_SECRET_KEY
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_BOOTSTRAP_TOKEN
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: POSTGRESQL_PASSWORD
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      fsGroup: 1000
    persistence:
      storageClass: local-hostpath
      size: 10Gi
