---
apiVersion: helm.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    authentik:
      error_reporting:
        enabled: false
    server:
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "auth.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    postgresql:
      enabled: true
    redis:
      enabled: true
    envFrom:
      - secretRef:
          name: authentik-secrets
    global:
      volumeMounts:
        - mountPath: /data
          name: authentik-data
      volumes:
        - name: authentik-data
          persistentVolumeClaim:
            claimName: authentik-data-pvc
