apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: security
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:GoDb3T4tIKdIoRD0P8UOpN2sK//suq7ofJqFba/Wq1eKk9dzWGAYpxcVuT7p0UaidX8=,iv:bE6W8PYselbumr77lPnsllCUzXPXloCyU0yEJv5fHW4=,tag:yxtm7TwZosYSOLuUksHvdw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:KoLSVukMYGOGQKlpyQhQEqXMTSp0TJqtr4KyHEA/q0LO3nOIX+zVKArL/siHdX6aVZErs7vPHkuMoDeXENWnraLAKnJBq792JTG4vu05SNc=,iv:suXoQjPI1ruUuX7PsgWoZD+Yqe1Eu2RqAlHmcW3IzG8=,tag:d6uRcXB5DkGKU1Vwa7qQmg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:7j0TbWQY4Xbi5gHCQ33N/6y64ILHco50IofB3d2pQmTVfCtnq3cFqw==,iv:RjqhpRuG6pBSzTtjtRwQPRp185nn7eAjdxStxbUtBrY=,tag:Hhyl8N6tfCe8jrULhJOeuA==,type:str]
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:KvPQEKzV7sLY0A02yMAh16w7b6qtsUVOBvKKL9vixedtubuWOiwXag==,iv:HRksYqMiwRYbP29tvHKwRyJOF9y1bdNd8klKbc+V/8o=,tag:Xo9NASr9zJVGa3zg7iyhXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM0RnVnVMb3ByMnNiZ0pF
            UGVIdEVoSGYxNW5ua0NMVFdkY2x2Tlc1UWpFClVMemtYTGU2K09FYVViUWhnWGJT
            MGZCcHlEK25SR1JKR1Nhc28vbEFNSnMKLS0tIGZ5a3F6NStjekdkUTdLMGhRb1hK
            NXZ4cjhaOWZTVkI5S2FyRFUraExTQUEKuWHjvK9S+b6JhIBFHj5UrKoN6uaW6Rn4
            g+fk5BAfxkyXGPRPgzUy/8cvgsBVjyyUiS4H0yokM8EgfOv1SsI6lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T13:33:23Z"
    mac: ENC[AES256_GCM,data:k6SI06T+2zmLrJvb73kYgGBA5uIl/gfSlYoe72XkZbyFHrEluxQJFIZUPXWMGH/4ezwcev+LX/Wwtz/KUdieslZ86I08hntlNWyeE3sDjQnXIvlrDPSX+M+UUpS/vf7jcKFMEE4QD9nYL44rw4rP5EgbkwzFKeCCjQ9sMFn9iBc=,iv:DldRRsMuEFaenh5cXj8EWGlnQ6fHV+EFpOq5Oa7pEWM=,tag:hLMGcG3KArYzqXrfg2/F6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
