apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
