kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  labels:
    app: jellyfin

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin

    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - name: jellyfin
              containerPort: 8096

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Stockholm"

          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
            - name: extracted-movies
              mountPath: /movies
            - name: extracted-series
              mountPath: /series

          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 400m
              memory: 400Mi

      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - name: extracted-series
          persistentVolumeClaim:
            claimName: extracted-series
        - name: extracted-movies
          persistentVolumeClaim:
            claimName: extracted-movies
