apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: home-automation
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    beta_bind_port: 0
    users: {}  # Changed from empty list to empty mapping
    language: "en"
    theme: "auto"
    dns:
      bind_host: 0.0.0.0
      port: 53
      protection_enabled: true
      filtering_enabled: true
      safebrowsing_enabled: true
      safesearch_enabled: true
      querylog_enabled: true
      ratelimit: 20
      blocked_response_ttl: 10
      bootstrap_dns: "1.1.1.1,8.8.8.8"  # Changed from a sequence to a comma-separated string
    tls:
      enabled: false
    log: ""  # Changed from a map of settings to a simple string
    security:
      protection_enabled: true
