apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: home-automation
  labels:
    app: adguard

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: copy-config
          image: busybox:latest
          command:
            - sh
            - -c
            - cp /config/AdGuardHome.yaml /writable/AdGuardHome.yaml
          volumeMounts:
            - name: adguard-config
              mountPath: /config
            - name: config-writable
              mountPath: /writable
      containers:
        - name: adguard
          image: adguard/adguardhome:v0.107.57
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
              ephemeral-storage: 1Gi
            limits:
              memory: 256Mi
              cpu: 300m
              ephemeral-storage: 2Gi
          env:
            - name: AGH_CONFIG
              value: /opt/adguardhome/conf/AdGuardHome.yaml
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/data
            - name: config-writable
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-pvc
        - name: adguard-config
          configMap:
            name: adguard-config
        - name: config-writable
          emptyDir: {}
