apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: home-automation
  labels:
    app: adguard

spec:
  selector:
    app: adguard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
  externalTrafficPolicy: Local
