apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
  namespace: home-automation
  labels:
    app: adguard

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
