apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker

  template:
    metadata:
      labels:
        app: speedtest-tracker

    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DISPLAY_TIMEZONE
              value: UTC
            - name: SPEEDTEST_SCHEDULE
              value: "*/5 * * * *"
            - name: SPEEDTEST_SERVERS
              value: "26852,53521,6061"
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: speedtest-db-connection
                  key: DB_CONNECTION
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-key
                  key: app-key
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: email
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker
