---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blocket-bot-db
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-hostpath
