apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
stringData:
    DB_CONNECTION: ENC[AES256_GCM,data:8hUIYig=,iv:Ju8mXWrYLDH+eMlUwtqZ4McknJGByGmMWdWQWjMnrwQ=,tag:i6ioTgqHwKobWVm/Xx5PnA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:D3MPP3Uvrlk=,iv:1TiHmw7OSyqShq9dUcncPQxtBFLxSsxZh8Ut85Cn1hU=,tag:8Bbon0cuUv6SVBx6UF+UhQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:voUOeg==,iv:s8grNa1Y1Nr7h8KotWpTIi5m4/5QXulI88q2/ZG8Ubc=,tag:WPev9VcFX5ZqolIOGSKe3g==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:8LZjqJKOM5UthtwHkanDhyE=,iv:9YG7yPf4AcSqPWXzLeoEo/UALj94IBAnnpVHHVOFRN0=,tag:k5qE2zQUcTxi6h7v3H9E/Q==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:fuzysq89,iv:LbKSMkh7thsZqI22mwv6u5PGMSa+pr9U55uzd1nmz2w=,tag:Tiwskq4lEF9SZrFjgfLS5Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ZspcBX0nEvg=,iv:1KMejN7OlMcLW+GZ8D+5J889O74jo7iVwI+3xa8WNGw=,tag:5RWg4EzQ0fVs3uku9BBwqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWnRzN0VBNzBaVFhMTTJ4
            ZXVhYnNKa2ZFSGlId0VnTG8xN1V0ZUdlcUZRClpuWXh4R1g2Z0FDQ3Nad3ZXemtJ
            bDNHOE1WTjRWdDdvTEpqUGZrbEJRY1UKLS0tIHRoSExCWHZiemZ4MllpMTV2Z0lB
            TGpEVExhR3BBaHhHTWxMbkljUFFWbm8KXUwpRUka2A/ttRN6FfFXePkvt0LagLNI
            szYPGGfC/U6EsUBTcCaBE6FEcdJIMUL6xpLHFimhB73ir1qg1yG9Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T21:49:53Z"
    mac: ENC[AES256_GCM,data:A01hwySWOODCGBetj0Fghwv3ilooJLOCyW224TxydOsG/gjfakhNP+aVgmzUDh03QYINTas1WW4mp2k6mtWSah4GjW98hkzJR0GJBz4QxpwmVU6Lhc1qHe1SQqesqlITqYGbwbjORW9hbEVepzpO/Ecr/A2eDngRie8mXUwAo7M=,iv:XtCdaovRhtsNOZLMaP4IcS+m1RuceMmbAjLuHTKcCTQ=,tag:LpRqjdka0m60pmqc2DXuxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
