apiVersion: v1
kind: Secret
metadata:
    name: speedtest-db-connection
stringData:
    DB_CONNECTION: ENC[AES256_GCM,data:JO8sClNp,iv:v1iCRiWPA5HC+OCH98KCcche0GYs3j8fXrHRYxt1em4=,tag:70TiVg9A/qXtTaLFp+v6lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v75sqdgw3dqnhazm3t8x5rzpyd2llkhtmh5te23e40pt20t8h3zsv6h7ld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOUVFblJmQlJzZUlKUXRo
            TVBnUXFCN0drSHlVYmNYL25xNjQ1cGxobFdZCkFBM2pJRGZXQXR0VFhocjh0SWIy
            LzRaMlZIZ05rejY4YWU0MFErVUZmNFkKLS0tIDBBUDBSRmdFNzFUbmkvM012S2Fl
            TUtjd1VZUzdscmdyVEJPS2RlUlVmUUUKm1qzyDUQHIWmwVtYej5Gwld7c2QNzM8e
            RgxE/fE0tZQkeGaXKDFoz1Pz7Pgb7wcTt+A5DNpj4gSkFxchbYZeAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T09:31:12Z"
    mac: ENC[AES256_GCM,data:D92skSk5BmlmvqqDG+dtzjioC3M9wfLabbY1OpMqTdqkOJ8vqJj+eic57jwjQUp04aleDzcOaJi+zfvmzhmnocG6wkh4FfgKFJ+HL057HbAL2pwqq3ioSnS6oA+FAXg6QYOWOCgFS74pgizqeHHLt5XXDQr/lvwzWV7vPjiaohc=,iv:Lv23/PO17iwqZhPplYI8zWQlSRSZw1YOw7r2MUgIcqc=,tag:7lAPJVM1feX9/OohsRx3nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
