apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      labels:
        app: qbittorrent
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - &host "qbittorrent.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    persistence:
      config:
        enabled: true
        storageClass: local-hostpath
        size: 1Gi
      downloads:
        enabled: true
        storageClass: local-hostpath
        size: 10Gi
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    env:
      TZ: "Europe/Stockholm"
      PUID: 1000
      PGID: 1000
