---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: gabe565
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "qbittorrent.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    global:
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Stockholm"
        - name: DOCKER_MODS
          value: "ghcr.io/gabe565/linuxserver-mod-vuetorrent"
    persistence:
      enabled: true
      storageClass: local-hostpath
      size: 10Gi
      vuetorrent:
        enabled: true
        type: emptyDir
