---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 5.0.4
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 5.0.4
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: TZ
                value: "${TIMEZONE}"
            ports:
              - containerPort: 8080
                name: web
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
    service:
      main:
        ports:
          web:
            port: 8080
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: web
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: pvc
        name: qbittorrent-config
        size: 1Gi
        storageClass: local-hostpath
      downloads:
        enabled: true
        type: pvc
        name: qbittorrent-downloads
        size: 10Gi
        storageClass: local-hostpath
